### ISSUE TITLE
Streamline the build process

### ISSUE THREAD

**Issue by redagito** [gameknife/gkEngine#16]
Hi, I hope english is ok as I do not speak or write chinese.

The build process of the engine, studio and tools is cumbersome and prone to error.
Downloading additonal files and executing .bat files adds an additional layer of complexity.
Is it possible or maybe already planned to use, for example, CMake for project generation/as meta build tool?
Instead of downloading additional libraries, using git submodules to include any external dependencies would be considered best practice (afaik) and thus very recommended.

Kind Regards

**Comment by gameknife** [comment]
@redagito thanks for you suggestion. I am working on a auto download & deploy script on both windows & osx. depends & media is aready store at http://github.com/gameKnife/gkengine-resource. And may the toolchain simple. CMake is a good suggestion, but the usage is a little bit complex. So, at this time, if auto deploy script is enough, that is good.
