### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gameknife/gkEngine#4]
I would like to point out that identifiers like "[`gkTerrian_h__`](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/engine/gkCore/gkTerrian.h#L39)" and "[`AFX_WORKSPACEVIEW_H__8B9758DA_BD65_4E68_BC3C_8C98B2419838__INCLUDED_`](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/editor/gkstudio/WorkspaceView.h#L28)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gameknife** [comment]
Thanks for the suggestion, this problem should be fixed. but now, this project in a one man project. I wish to gain a team to develop gkEngine. So, if u get some time and interested on this, please fix the issues that u discoverd and create a pull request. welcome to join me!

by the way, I haven't provide an english version of deploy guide, did u deploy and success run this 3d engine?

thanks, 

Kaiming

**Comment by GraphicGame** [comment]
well, I can translate the chinese version of deploy guide into english.

**Comment by GraphicGame** [comment]
translating now!  just a moment.

**Comment by GraphicGame** [comment]
Hi, man, the english version of deploy guide for window has been worked now. https://github.com/gameknife/gkEngine/wiki/Deployment-guide-on-windows-plantform

**Comment by GraphicGame** [comment]
Hi,man, if you have some trouble on understanding the guide, say it loudly.

**Comment by gameknife** [comment]
not hurry issue may fix in a long time later, close now.

**Comment by elfring** [comment]
I find it better to keep such issues open until the affected implementation details will really be fixed.
