### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [gameknife/gkEngine#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [CSplineVec3Track](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/engine/gkTrackBus/TSplineTrack.cpp#L22)
- [Image::release](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/editor/gkResourceCompiler/Image.cpp#L202)
- [MemoryOutputStream](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/engine/gkPhysX/source/gkPhysXStream.cpp#L13)

**Comment by gameknife** [comment]
Thanks for your suggestion, this issue will be fixed by me or other future team member in some time later. Now it will not cause some critical problem.

Kaiming

**Comment by gameknife** [comment]
not hurry issue may fix in a long time later, close now.
