### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [gameknife/gkEngine#6]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [utf8Compiler::encode](https://github.com/gameknife/gkEngine/blob/a1c2b354cd4fe21973cb00ef5fb37acabe45e695/code/editor/gkResourceCompiler/txtCompiler.cpp#L43)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [IEvent constructor](https://github.com/gameknife/gkEngine/blob/4647acdc2ee949bc016832a5469f348bb5317ba6/code/engine/gkCommon/IEvent.h#L180)

**Comment by gameknife** [comment]
Thanks a lot. I will fix them in later updates.

Kaiming

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by gameknife** [comment]
not hurry issue may fix in a long time later, close now.
